language: c
sudo: required
install:
  - bash -ex ocaml-ci-scripts/.travis-ocaml.sh
  - eval $(opam config env)
  - opam install js_of_ocaml menhir omake ounit
script:
  - omake
  - omake test
env:
  - OCAML_VERSION=4.02 OPAMYES=1
  - OCAML_VERSION=4.03 OPAMYES=1
  - OCAML_VERSION=4.04 OPAMYES=1
os:
  - linux
cache:
  directories:
    - "$HOME/.opam"
notifications:
  slack:
    secure: N5l/rGJvfJuk230Vol4lN00sHcI8DVjuV5L6dE04tPYVUU1XUka/slzNpkCqavQRbkPv4TI+OOe6pBSbAdkj1Wo9xpQGNUelvRlbgpti4NB36fhP9gAzeKF3bGJoi00sb9FJ+WmGZuJZKGaUGMxYfa+EH+ALz3Rgig/bwOXZR/xRw0A9lkfBoymN3v7tR727x+OdVXHvZZIsYMnN7kP9zMs6BZWgLNzEz9K+rirRbsNn/HpHf1yC3JQuWyT59GXXNOwQk6/mzHARYuH8Zq3hNNGfRfhVa0OOZslVFDOI/J1UyYsURmaWaD7zcAq4S3vtnmV8MVHr8M5Fo6fhaTY7Ot3IZAmivyNjeAhXFw6LjKIh4LWj8t11j3rZCkK+cKFr1Bmu+bfYEiq88oD7Bmi3VaqnXxYwfHQ/iP9Oq+p7SophJszoleIWACac1JEko9/2dsGiPGCBpWH6uG0sTsvcqByBa9r29R9OFvTSLp5+GBWJZ07/bi3y14DGpKRqikDsP8yTwPY0eRn3WB/JbkMvQvZf3e5zmWSPHzA9V9qrAXDlh3tq/KUQ9rnT5mbS3xLKh+PfQEZtrDW+Eksm9DtUhNDUuL6ywEHiUZy6uBjMIFg58Na+sap/rIaQ7Y8PaLb5/guf7FDLIcXXVumYm5cFiTKiubRmfTbiyVGWv1gJHrw=
